-- Contributor invites: lets admins grant the 'contributor' role to people by
-- email before they ever sign up, via Supabase's own invite-by-email flow.
create table public.contributor_invites (
	id bigint generated by default as identity primary key,
	email text not null,
	role public.user_role not null default 'contributor',
	invited_by uuid references auth.users on delete set null,
	created_at timestamp with time zone not null default timezone('utc'::text, now()),
	used_at timestamp with time zone
);
-- Callers are expected to store/lookup emails already lower-cased (see the
-- invite action and the handle_new_user() trigger below).
create unique index contributor_invites_email_idx on public.contributor_invites (email);

alter table public.contributor_invites enable row level security;

create policy "Allow admins to read contributor invites" on public.contributor_invites for
select using (
		(
			select authorize('user_roles.update')
		)
	);
create policy "Allow admins to create contributor invites" on public.contributor_invites for
insert with check (
		(
			select authorize('user_roles.update')
		)
	);
create policy "Allow admins to update contributor invites" on public.contributor_invites for
update using (
		(
			select authorize('user_roles.update')
		)
	);

-- Re-created to also assign the role from a matching, unused invite instead of
-- always defaulting new users to 'user'. Role assignment intentionally reads
-- from this server-populated table rather than raw_user_meta_data, since the
-- latter can be set by anyone via a normal supabase.auth.signUp() call.
--
-- Note: this trigger fires the moment an invite is sent (inviteUserByEmail
-- creates the auth.users row immediately), not when the person actually opens
-- the email or accepts. It intentionally does NOT mark the invite as used -
-- that only happens once the person completes /accept-invite, so the admin
-- UI's pending/accepted status reflects real completion, not just that an
-- invite was sent.
create or replace function public.handle_new_user() returns trigger language plpgsql security definer
set search_path = public as $$
declare
	invite public.contributor_invites%rowtype;
	assigned_role public.user_role := 'user';
begin
	select * into invite
	from public.contributor_invites
	where lower(email) = lower(new.email)
		and used_at is null
	limit 1;

	if found then
		assigned_role := invite.role;
	end if;

	insert into public.user_roles (id, role)
	values (new.id, assigned_role);
	insert into public.profiles (id, email, type, display_name)
	values (
			new.id,
			new.email,
			(
				select slug
				from public.user_types
				where is_default = true
			),
			-- Invited users have no display_name yet (they set it on the
			-- accept-invite page after account creation); the column is
			-- NOT NULL, so fall back to an empty string rather than null.
			coalesce(new.raw_user_meta_data->>'display_name', '')
		);
	return new;
end;
$$;
