create extension if not exists "unaccent" with schema "public" version '1.1';
create sequence "public"."comments_id_seq";
drop trigger if exists "handle_updated_at" on "public"."branding";
drop trigger if exists "handle_updated_at" on "public"."events";
drop trigger if exists "handle_updated_at" on "public"."guides";
drop trigger if exists "handle_updated_at" on "public"."map_pins";
drop trigger if exists "handle_updated_at" on "public"."profiles";
drop view if exists "public"."profiles_view";
create table "public"."crowdsource_comments" (
    "id" integer not null default nextval('comments_id_seq'::regclass),
    "user_id" uuid,
    "sign_id" bigint,
    "parent_id" integer,
    "content_text" text,
    "content_video" text,
    "created_at" timestamp without time zone default now(),
    "last_edited_at" timestamp without time zone
);
alter table "public"."crowdsource_comments" enable row level security;
create table "public"."islr_contributors" (
    "id" uuid not null,
    "consented_at" timestamp with time zone not null default now()
);
alter table "public"."islr_contributors" enable row level security;
create table "public"."islr_submission_votes" (
    "id" bigint generated always as identity not null,
    "submission_id" bigint not null,
    "reviewer_id" uuid not null,
    "approved" boolean not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now())
);
alter table "public"."islr_submission_votes" enable row level security;
create table "public"."islr_submissions" (
    "id" bigint generated always as identity not null,
    "sign_id" bigint not null,
    "contributor_id" uuid not null,
    "video" text not null,
    "status" moderation_status not null default 'pending'::moderation_status,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now())
);
alter table "public"."islr_submissions" enable row level security;
create table "public"."parameters" (
    "id" bigint not null,
    "tipo" character varying,
    "code" character varying,
    "name" text,
    "is_parent" boolean,
    "children" character varying[],
    "parent" character varying,
    "image" text
);
alter table "public"."parameters" enable row level security;
create table "public"."signs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone,
    "name" text,
    "video" text,
    "annotation" jsonb,
    "is_anotated" bigint,
    "last_changed" timestamp with time zone,
    "annotation_array" bigint[],
    "description" text,
    "context_video" text,
    "sentence" text,
    "frequency" bigint,
    "theme_flattened" text,
    "theme" text[],
    "district" text,
    "image" text,
    "game_video" text,
    "created_by_user_id" uuid,
    "annotated_by_user_id" uuid,
    "main_sign_id" bigint,
    "name_unaccented" text,
    "context_video_2" text,
    "sentence_2" text,
    "dictionary" text
);
alter table "public"."signs" enable row level security;
create table "public"."signs_backup_themes_20260817" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone,
    "name" text,
    "video" text,
    "annotation" jsonb,
    "is_anotated" bigint,
    "last_changed" timestamp with time zone,
    "annotation_array" bigint[],
    "description" text,
    "context_video" text,
    "sentence" text,
    "frequency" bigint,
    "theme_flattened" text,
    "theme" text[],
    "district" text,
    "image" text,
    "game_video" text,
    "created_by_user_id" uuid,
    "annotated_by_user_id" uuid,
    "main_sign_id" bigint,
    "name_unaccented" text,
    "context_video_2" text,
    "sentence_2" text,
    "dictionary" text
);
alter table "public"."signs_backup_themes_20260817" enable row level security;
create table "public"."signs_dictionary_backup_20260817" (
    "id" bigint not null,
    "previous_dictionary" text,
    "theme_at_update" text[],
    "backed_up_at" timestamp with time zone
);
alter table "public"."signs_dictionary_backup_20260817" enable row level security;
create table "public"."signs_favorite" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default now(),
    "user_id" uuid default auth.uid(),
    "sign_id" bigint
);
alter table "public"."signs_favorite" enable row level security;
create table "public"."signs_moderation" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "sign_id" bigint,
    "created_by_user_id" uuid,
    "status" moderation_status,
    "comment" text
);
alter table "public"."signs_moderation" enable row level security;
create table "public"."signs_rating" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default now(),
    "user_id" uuid default auth.uid(),
    "sign_id" bigint,
    "value" bigint
);
alter table "public"."signs_rating" enable row level security;
alter table "public"."notifications" enable row level security;
alter table "public"."profiles" add column "age" bigint;
alter table "public"."profiles" add column "cnum" text;
alter table "public"."profiles" add column "gender" text;
alter table "public"."profiles" add column "language" text;
alter table "public"."profiles" add column "profession" text;
alter table "public"."profiles" add column "sign_name" text;
alter sequence "public"."comments_id_seq" owned by "public"."crowdsource_comments"."id";
CREATE UNIQUE INDEX comments_pkey ON public.crowdsource_comments USING btree (id);
CREATE UNIQUE INDEX islr_contributors_pkey ON public.islr_contributors USING btree (id);
CREATE UNIQUE INDEX islr_submission_votes_pkey ON public.islr_submission_votes USING btree (id);
CREATE UNIQUE INDEX islr_submission_votes_submission_id_reviewer_id_key ON public.islr_submission_votes USING btree (submission_id, reviewer_id);
CREATE UNIQUE INDEX islr_submissions_pkey ON public.islr_submissions USING btree (id);
CREATE UNIQUE INDEX parameters_pkey ON public.parameters USING btree (id);
CREATE UNIQUE INDEX signs_backup_themes_20260817_pkey ON public.signs_backup_themes_20260817 USING btree (id);
CREATE UNIQUE INDEX signs_dictionary_backup_20260817_pkey ON public.signs_dictionary_backup_20260817 USING btree (id);
CREATE UNIQUE INDEX signs_favorite_pkey ON public.signs_favorite USING btree (id);
CREATE UNIQUE INDEX signs_moderation_pkey ON public.signs_moderation USING btree (id);
CREATE UNIQUE INDEX signs_pkey ON public.signs USING btree (id);
CREATE UNIQUE INDEX signs_rating_pkey ON public.signs_rating USING btree (id);
CREATE UNIQUE INDEX unique_sign_user ON public.signs_rating USING btree (sign_id, user_id);
alter table "public"."crowdsource_comments" add constraint "comments_pkey" PRIMARY KEY using index "comments_pkey";
alter table "public"."islr_contributors" add constraint "islr_contributors_pkey" PRIMARY KEY using index "islr_contributors_pkey";
alter table "public"."islr_submission_votes" add constraint "islr_submission_votes_pkey" PRIMARY KEY using index "islr_submission_votes_pkey";
alter table "public"."islr_submissions" add constraint "islr_submissions_pkey" PRIMARY KEY using index "islr_submissions_pkey";
alter table "public"."parameters" add constraint "parameters_pkey" PRIMARY KEY using index "parameters_pkey";
alter table "public"."signs" add constraint "signs_pkey" PRIMARY KEY using index "signs_pkey";
alter table "public"."signs_backup_themes_20260817" add constraint "signs_backup_themes_20260817_pkey" PRIMARY KEY using index "signs_backup_themes_20260817_pkey";
alter table "public"."signs_dictionary_backup_20260817" add constraint "signs_dictionary_backup_20260817_pkey" PRIMARY KEY using index "signs_dictionary_backup_20260817_pkey";
alter table "public"."signs_favorite" add constraint "signs_favorite_pkey" PRIMARY KEY using index "signs_favorite_pkey";
alter table "public"."signs_moderation" add constraint "signs_moderation_pkey" PRIMARY KEY using index "signs_moderation_pkey";
alter table "public"."signs_rating" add constraint "signs_rating_pkey" PRIMARY KEY using index "signs_rating_pkey";
alter table "public"."crowdsource_comments" add constraint "comments_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES crowdsource_comments(id) ON DELETE CASCADE not valid;
alter table "public"."crowdsource_comments" validate constraint "comments_parent_id_fkey";
alter table "public"."crowdsource_comments" add constraint "comments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table "public"."crowdsource_comments" validate constraint "comments_user_id_fkey";
alter table "public"."crowdsource_comments" add constraint "crowdsource_comments_sign_id_fkey" FOREIGN KEY (sign_id) REFERENCES signs(id) ON DELETE CASCADE not valid;
alter table "public"."crowdsource_comments" validate constraint "crowdsource_comments_sign_id_fkey";
alter table "public"."islr_contributors" add constraint "islr_contributors_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;
alter table "public"."islr_contributors" validate constraint "islr_contributors_id_fkey";
alter table "public"."islr_submission_votes" add constraint "islr_submission_votes_reviewer_id_fkey" FOREIGN KEY (reviewer_id) REFERENCES auth.users(id) not valid;
alter table "public"."islr_submission_votes" validate constraint "islr_submission_votes_reviewer_id_fkey";
alter table "public"."islr_submission_votes" add constraint "islr_submission_votes_submission_id_fkey" FOREIGN KEY (submission_id) REFERENCES islr_submissions(id) not valid;
alter table "public"."islr_submission_votes" validate constraint "islr_submission_votes_submission_id_fkey";
alter table "public"."islr_submission_votes" add constraint "islr_submission_votes_submission_id_reviewer_id_key" UNIQUE using index "islr_submission_votes_submission_id_reviewer_id_key";
alter table "public"."islr_submissions" add constraint "islr_submissions_contributor_id_fkey" FOREIGN KEY (contributor_id) REFERENCES auth.users(id) not valid;
alter table "public"."islr_submissions" validate constraint "islr_submissions_contributor_id_fkey";
alter table "public"."islr_submissions" add constraint "islr_submissions_sign_id_fkey" FOREIGN KEY (sign_id) REFERENCES signs(id) not valid;
alter table "public"."islr_submissions" validate constraint "islr_submissions_sign_id_fkey";
alter table "public"."signs" add constraint "signs_annotated_by_user_id_fkey" FOREIGN KEY (annotated_by_user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table "public"."signs" validate constraint "signs_annotated_by_user_id_fkey";
alter table "public"."signs" add constraint "signs_created_by_user_id_fkey" FOREIGN KEY (created_by_user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table "public"."signs" validate constraint "signs_created_by_user_id_fkey";
alter table "public"."signs" add constraint "signs_main_sign_id_fkey" FOREIGN KEY (main_sign_id) REFERENCES signs(id) not valid;
alter table "public"."signs" validate constraint "signs_main_sign_id_fkey";
alter table "public"."signs_backup_themes_20260817" add constraint "signs_backup_themes_20260817_annotated_by_user_id_fkey" FOREIGN KEY (annotated_by_user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table "public"."signs_backup_themes_20260817" validate constraint "signs_backup_themes_20260817_annotated_by_user_id_fkey";
alter table "public"."signs_backup_themes_20260817" add constraint "signs_backup_themes_20260817_created_by_user_id_fkey" FOREIGN KEY (created_by_user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table "public"."signs_backup_themes_20260817" validate constraint "signs_backup_themes_20260817_created_by_user_id_fkey";
alter table "public"."signs_backup_themes_20260817" add constraint "signs_backup_themes_20260817_main_sign_id_fkey" FOREIGN KEY (main_sign_id) REFERENCES signs(id) not valid;
alter table "public"."signs_backup_themes_20260817" validate constraint "signs_backup_themes_20260817_main_sign_id_fkey";
alter table "public"."signs_favorite" add constraint "signs_favorite_sign_id_fkey" FOREIGN KEY (sign_id) REFERENCES signs(id) ON DELETE CASCADE not valid;
alter table "public"."signs_favorite" validate constraint "signs_favorite_sign_id_fkey";
alter table "public"."signs_favorite" add constraint "signs_favorite_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;
alter table "public"."signs_favorite" validate constraint "signs_favorite_user_id_fkey";
alter table "public"."signs_moderation" add constraint "signs_moderation_created_by_user_id_fkey" FOREIGN KEY (created_by_user_id) REFERENCES profiles(id) not valid;
alter table "public"."signs_moderation" validate constraint "signs_moderation_created_by_user_id_fkey";
alter table "public"."signs_moderation" add constraint "signs_moderation_sign_id_fkey" FOREIGN KEY (sign_id) REFERENCES signs(id) ON DELETE CASCADE not valid;
alter table "public"."signs_moderation" validate constraint "signs_moderation_sign_id_fkey";
alter table "public"."signs_rating" add constraint "signs_rating_sign_id_fkey" FOREIGN KEY (sign_id) REFERENCES signs(id) ON DELETE CASCADE not valid;
alter table "public"."signs_rating" validate constraint "signs_rating_sign_id_fkey";
alter table "public"."signs_rating" add constraint "signs_rating_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;
alter table "public"."signs_rating" validate constraint "signs_rating_user_id_fkey";
alter table "public"."signs_rating" add constraint "unique_sign_user" UNIQUE using index "unique_sign_user";
set check_function_bodies = off;
CREATE OR REPLACE FUNCTION public.auto_lock_post()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.created_at < NOW() - INTERVAL '7 days' THEN
    NEW.is_locked := TRUE;
  END IF;
  RETURN NEW;
END;
$function$;
CREATE OR REPLACE FUNCTION public.check_islr_submission_vote_limit()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  vote_count int;
begin
  perform 1 from public.islr_submissions where id = new.submission_id for update;

  select count(*) into vote_count
  from public.islr_submission_votes
  where submission_id = new.submission_id;

  if vote_count >= 3 then
    raise exception 'Esta submissão já tem 3 votos.';
  end if;

  return new;
end;
$function$;
CREATE OR REPLACE FUNCTION public.get_closest_signs(query_array bigint[], limit_count integer, offset_count integer)
 RETURNS TABLE(id bigint, created_at timestamp with time zone, name text, video text, annotation jsonb, theme text[], is_anotated bigint, last_changed timestamp with time zone, description text, annotation_array bigint[], context_video text, sentence text, frequency bigint, theme_flattened text, district text)
 LANGUAGE plpgsql
 SET statement_timeout TO '10s'
AS $function$BEGIN

  RETURN QUERY
  WITH scored_signs AS (
    SELECT 
      s.id,
      s.created_at,
      s.name,
      s.video,
      s.annotation,
      s.theme,
      s.is_anotated,
      s.last_changed,
      s.description,
      s.annotation_array,
      s.context_video,
      s.sentence,
      s.frequency,
      s.theme_flattened,
      s.district,
      score_calc.score
    FROM signs s
    CROSS JOIN LATERAL (
      SELECT COALESCE(SUM(
        CASE
          WHEN s.annotation_array[qi] = 1 THEN
            5 *
            CASE qp.tipo
              WHEN 'configuracao' THEN 100
              WHEN 'localizacao' THEN 90
              WHEN 'movimento' THEN 80
              WHEN 'orientacao' THEN 70
              WHEN 'expressao facial' THEN 60
              ELSE 0
            END

          WHEN EXISTS (
            SELECT 1
            FROM generate_subscripts(s.annotation_array, 1) AS si
            JOIN parameters sp ON sp.id = si
            WHERE s.annotation_array[si] = 1
              AND qp.parent IS NOT NULL
              AND qp.parent <> ''
              AND sp.parent = qp.parent
              AND sp.code <> qp.code
          ) THEN
            3 *
            CASE qp.tipo
              WHEN 'configuracao' THEN 100
              WHEN 'localizacao' THEN 90
              WHEN 'movimento' THEN 80
              WHEN 'orientacao' THEN 70
              WHEN 'expressao facial' THEN 60
              ELSE 0
            END

          WHEN EXISTS (
            SELECT 1
            FROM generate_subscripts(s.annotation_array, 1) AS si
            JOIN parameters sp ON sp.id = si
            WHERE s.annotation_array[si] = 1
              AND sp.code = qp.parent
          ) THEN
            3 *
            CASE qp.tipo
              WHEN 'configuracao' THEN 100
              WHEN 'localizacao' THEN 90
              WHEN 'movimento' THEN 80
              WHEN 'orientacao' THEN 70
              WHEN 'expressao facial' THEN 60
              ELSE 0
            END

          WHEN EXISTS (
            SELECT 1
            FROM generate_subscripts(s.annotation_array, 1) AS si
            JOIN parameters sp ON sp.id = si
            WHERE s.annotation_array[si] = 1
              AND sp.code = ANY(qp.children)
          ) THEN
            3 *
            CASE qp.tipo
              WHEN 'configuracao' THEN 100
              WHEN 'localizacao' THEN 90
              WHEN 'movimento' THEN 80
              WHEN 'orientacao' THEN 70
              WHEN 'expressao facial' THEN 60
              ELSE 0
            END

          ELSE 0
        END
      ), 0) AS score
      FROM generate_subscripts(query_array, 1) AS qi
      JOIN parameters qp ON qp.id = qi
      WHERE query_array[qi] = 1
    ) score_calc
    WHERE CAST(s.is_anotated AS INTEGER) = 2
      AND COALESCE(s.theme_flattened, '') NOT ILIKE '%CEB%'
      AND COALESCE(s.theme_flattened, '') NOT ILIKE '%Filmar%'
  )

  SELECT
    ss.id,
    ss.created_at,
    ss.name,
    ss.video,
    ss.annotation,
    ss.theme,
    ss.is_anotated,
    ss.last_changed,
    ss.description,
    ss.annotation_array,
    ss.context_video,
    ss.sentence,
    ss.frequency,
    ss.theme_flattened,
    ss.district
  FROM scored_signs ss
  WHERE ss.score > 0
  ORDER BY ss.score DESC, ss.name ASC;

END;$function$;
CREATE OR REPLACE FUNCTION public.get_closest_signs_fc(query_array bigint[], limit_count integer, offset_count integer)
 RETURNS TABLE(id bigint, created_at timestamp with time zone, name text, video text, annotation jsonb, theme text[], is_anotated bigint, last_changed timestamp with time zone, description text, annotation_array bigint[], context_video text, sentence text, frequency bigint, theme_flattened text, district text)
 LANGUAGE plpgsql
 SET statement_timeout TO '10s'
AS $function$BEGIN

  RETURN QUERY
  WITH scored_signs AS (
    SELECT 
      s.id,
      s.created_at,
      s.name,
      s.video,
      s.annotation,
      s.theme,
      s.is_anotated,
      s.last_changed,
      s.description,
      s.annotation_array,
      s.context_video,
      s.sentence,
      s.frequency,
      s.theme_flattened,
      s.district,
      score_calc.score
    FROM signs s
    CROSS JOIN LATERAL (
      SELECT COALESCE(SUM(
        CASE
          WHEN s.annotation_array[qi] = 1 THEN
            5 *
            CASE qp.tipo
              WHEN 'configuracao' THEN 100
              WHEN 'localizacao' THEN 90
              WHEN 'movimento' THEN 80
              WHEN 'orientacao' THEN 70
              WHEN 'expressao facial' THEN 60
              ELSE 0
            END

          WHEN EXISTS (
            SELECT 1
            FROM generate_subscripts(s.annotation_array, 1) AS si
            JOIN parameters sp ON sp.id = si
            WHERE s.annotation_array[si] = 1
              AND qp.parent IS NOT NULL
              AND qp.parent <> ''
              AND sp.parent = qp.parent
              AND sp.code <> qp.code
          ) THEN
            3 *
            CASE qp.tipo
              WHEN 'configuracao' THEN 100
              WHEN 'localizacao' THEN 90
              WHEN 'movimento' THEN 80
              WHEN 'orientacao' THEN 70
              WHEN 'expressao facial' THEN 60
              ELSE 0
            END

          WHEN EXISTS (
            SELECT 1
            FROM generate_subscripts(s.annotation_array, 1) AS si
            JOIN parameters sp ON sp.id = si
            WHERE s.annotation_array[si] = 1
              AND sp.code = qp.parent
          ) THEN
            3 *
            CASE qp.tipo
              WHEN 'configuracao' THEN 100
              WHEN 'localizacao' THEN 90
              WHEN 'movimento' THEN 80
              WHEN 'orientacao' THEN 70
              WHEN 'expressao facial' THEN 60
              ELSE 0
            END

          WHEN EXISTS (
            SELECT 1
            FROM generate_subscripts(s.annotation_array, 1) AS si
            JOIN parameters sp ON sp.id = si
            WHERE s.annotation_array[si] = 1
              AND sp.code = ANY(qp.children)
          ) THEN
            3 *
            CASE qp.tipo
              WHEN 'configuracao' THEN 100
              WHEN 'localizacao' THEN 90
              WHEN 'movimento' THEN 80
              WHEN 'orientacao' THEN 70
              WHEN 'expressao facial' THEN 60
              ELSE 0
            END

          ELSE 0
        END
      ), 0) AS score
      FROM generate_subscripts(query_array, 1) AS qi
      JOIN parameters qp ON qp.id = qi
      WHERE query_array[qi] = 1
    ) score_calc
    WHERE CAST(s.is_anotated AS INTEGER) = 2
      AND COALESCE(s.theme_flattened, '') ILIKE '%CEB%'
      OR COALESCE(s.theme_flattened, '') ILIKE '%DACTILOLOGIA%'
      AND COALESCE(s.theme_flattened, '') NOT ILIKE '%Filmar%'
  )

  SELECT
    ss.id,
    ss.created_at,
    ss.name,
    ss.video,
    ss.annotation,
    ss.theme,
    ss.is_anotated,
    ss.last_changed,
    ss.description,
    ss.annotation_array,
    ss.context_video,
    ss.sentence,
    ss.frequency,
    ss.theme_flattened,
    ss.district
  FROM scored_signs ss
  WHERE ss.score > 0
  ORDER BY ss.score DESC, ss.name ASC;

END;$function$;
CREATE OR REPLACE FUNCTION public.hamming_distance(array1 bigint[], array2 bigint[])
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
  distance INTEGER := 0;
BEGIN
  IF cardinality(array1) != cardinality(array2) THEN
    RAISE EXCEPTION 'Arrays must be of the same length';
  END IF;

  FOR i IN 1..cardinality(array1) LOOP
    IF array1[i] != array2[i] THEN
      distance := distance + 1;
    END IF;
  END LOOP;

  RETURN distance;
END;
$function$;
CREATE OR REPLACE FUNCTION public.handle_islr_submission_vote()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  vote_count int;
  approve_count int;
begin
  select count(*), count(*) filter (where approved)
  into vote_count, approve_count
  from public.islr_submission_votes
  where submission_id = new.submission_id;

  if vote_count >= 3 then
    update public.islr_submissions
    set status = case when approve_count > 1 then 'approved' else 'rejected' end
    where id = new.submission_id;
  end if;

  return new;
end;
$function$;
CREATE OR REPLACE FUNCTION public.handle_sign_moderation_updates()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  if new.theme = ARRAY['Proposta - Em Discussão'] and new.theme_flattened = 'Proposta - Em Discussão' then
    insert into public.signs_moderation (sign_id, created_by_user_id, status, comment)
    values (
      new.id,
      new.created_by_user_id,
      'pending',
      'Pending moderation'
    );
  end if;

  return new;
end;
$function$;
CREATE OR REPLACE FUNCTION public.handle_signs_moderation_notification()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  notification_type notification_type;
  theme_check boolean;
begin
  -- Lookup the related sign and check theme conditions
  select 
    (s.theme = ARRAY['Proposta - Em Discussão'] and s.theme_flattened = 'Proposta - Em Discussão')
  into theme_check
  from public.signs s
  where s.id = new.sign_id;

  -- Only insert notification if theme matches
  if theme_check then
    if new.status = 'pending' then
      notification_type := 'sign_pending';
    elsif new.status = 'changes_requested' then
      notification_type := 'sign_changes_requested';
    elsif new.status = 'approved' then
      notification_type := 'sign_approved';
    elsif new.status = 'rejected' then
      notification_type := 'sign_rejected';
    end if;

    insert into public.notifications (user_id, type, data)
    values (
      new.created_by_user_id,
      notification_type,
      jsonb_build_object('sign_id', new.sign_id)
    );
  end if;

  return new;
end;
$function$;
create or replace view "public"."latest_signs_moderation" as  SELECT DISTINCT ON (signs_moderation.sign_id) signs_moderation.id,
    signs_moderation.inserted_at,
    signs_moderation.sign_id,
    signs_moderation.created_by_user_id AS user_id,
    signs_moderation.status,
    signs_moderation.comment
   FROM signs_moderation
  ORDER BY signs_moderation.sign_id, signs_moderation.inserted_at DESC;
CREATE OR REPLACE FUNCTION public.search_name(term text)
 RETURNS SETOF signs
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN QUERY
  SELECT *
  FROM signs
  WHERE unaccent(name) ILIKE unaccent('%' || term || '%');
END;
$function$;
CREATE OR REPLACE FUNCTION public.search_unaccent_name(search_term text)
 RETURNS SETOF signs
 LANGUAGE sql
 STABLE
AS $function$
  select * from signs
  where unaccent(name) ilike unaccent('%' || search_term || '%');
$function$;
CREATE OR REPLACE FUNCTION public.set_unaccented_name()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.name_unaccented := unaccent_text(NEW.name);
  RETURN NEW;
END;
$function$;
create or replace view "public"."signs_districts" as  SELECT btrim(signs.district) AS district,
    count(*) AS count
   FROM signs
  WHERE ((signs.district IS NOT NULL) AND (btrim(signs.district) <> ''::text))
  GROUP BY (btrim(signs.district))
  ORDER BY (count(*)) DESC, (btrim(signs.district));
create or replace view "public"."signs_favorite_view" as  SELECT f.id,
    f.user_id,
    f.sign_id,
    f.inserted_at,
    s.name
   FROM (signs_favorite f
     JOIN signs s ON ((f.sign_id = s.id)));
create or replace view "public"."signs_statistics" as  SELECT s.id,
    s.name,
    s.video,
    s.created_by_user_id,
    s.theme,
    s.theme_flattened,
    COALESCE(sum(
        CASE
            WHEN (sr.value = 1) THEN 1
            ELSE 0
        END), (0)::bigint) AS pos_votes,
    COALESCE(sum(
        CASE
            WHEN (sr.value = '-1'::integer) THEN 1
            ELSE 0
        END), (0)::bigint) AS neg_votes,
    COALESCE(sum(
        CASE
            WHEN (sr.value = 0) THEN 1
            ELSE 0
        END), (0)::bigint) AS nt_votes
   FROM (signs s
     LEFT JOIN signs_rating sr ON ((s.id = sr.sign_id)))
  GROUP BY s.id, s.name, s.video, s.created_by_user_id, s.theme, s.theme_flattened;
create or replace view "public"."signs_summary" as  SELECT s.id,
    s.name,
    s.created_at,
    s.video,
    s.created_by_user_id,
    s.theme,
    s.theme_flattened,
    COALESCE(sum(
        CASE
            WHEN (sr.value = 1) THEN 1
            ELSE 0
        END), (0)::bigint) AS positive_votes,
    COALESCE(sum(
        CASE
            WHEN (sr.value = '-1'::integer) THEN 1
            ELSE 0
        END), (0)::bigint) AS negative_votes,
    COALESCE(cc.total_comments, (0)::bigint) AS total_comments
   FROM ((signs s
     LEFT JOIN signs_rating sr ON ((s.id = sr.sign_id)))
     LEFT JOIN ( SELECT crowdsource_comments.sign_id,
            count(*) AS total_comments
           FROM crowdsource_comments
          GROUP BY crowdsource_comments.sign_id) cc ON ((s.id = cc.sign_id)))
  GROUP BY s.id, s.name, s.created_at, s.video, s.created_by_user_id, s.theme, s.theme_flattened, cc.total_comments
  ORDER BY s.created_at DESC;
create or replace view "public"."signs_themes" as  SELECT TRIM(BOTH FROM themes_split.theme) AS theme,
    count(*) AS count
   FROM ( SELECT unnest(string_to_array(signs.theme_flattened, ','::text)) AS theme
           FROM signs) themes_split
  GROUP BY (TRIM(BOTH FROM themes_split.theme))
  ORDER BY (count(*)) DESC;
create or replace view "public"."signs_view" as  SELECT s.id,
    s.created_at,
    s.name,
    s.video,
    s.annotation,
    s.is_anotated,
    s.last_changed,
    s.annotation_array,
    s.description,
    s.context_video,
    s.sentence,
    s.frequency,
    s.theme_flattened,
    s.theme,
    s.district,
    s.image,
    s.game_video,
    s.created_by_user_id,
    s.annotated_by_user_id,
    s.main_sign_id,
    sm.status,
    sm.comment
   FROM (signs s
     LEFT JOIN signs_moderation sm ON ((s.id = sm.sign_id)))
  WHERE (sm.status = 'pending'::moderation_status);
CREATE OR REPLACE FUNCTION public.unaccent_text(text_input text)
 RETURNS text
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
BEGIN
  RETURN translate(
    text_input,
    'áàâãäåāăąǎǻÁÀÂÃÄÅĀĂĄǍǺéèêëēĕėęěÉÈÊËĒĔĖĘĚíìîïĩīĭįıǐÍÌÎÏĨĪĬĮİǏóòôõöøōŏőǒǿÓÒÔÕÖØŌŎŐǑǾúùûüũūŭůűųǔǖǘǚǜÚÙÛÜŨŪŬŮŰŲǓǕǗǙǛýÿŷÝŸŶçćĉċčÇĆĈĊČñńņňÑŃŅŇ',
    'aaaaaaaaaaaAAAAAAAAAAAAeeeeeeeeeEEEEEEEEEiiiiiiiiiIIIIIIIIIoooooooooooOOOOOOOOOOOuuuuuuuuuuuuuuuUUUUUUUUUUUUUUUyyyYYYcccccCCCCCnnnnnNNNN'
  );
END;
$function$;
CREATE OR REPLACE FUNCTION public.update_theme_flattened()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.theme_flattened := (
    SELECT string_agg(value::text, ', ')
    FROM jsonb_array_elements_text(NEW.theme)
  );
  RETURN NEW;
END;
$function$;
CREATE OR REPLACE FUNCTION public.authorize(requested_permission user_permission)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare bind_permissions int;
user_role public.user_role;
begin -- Fetch user role once and store it to reduce number of calls
select (auth.jwt()->>'user_role')::public.user_role into user_role;
select count(*) into bind_permissions
from public.role_permissions
where role_permissions.permission = requested_permission
	and role_permissions.role = user_role;
return bind_permissions > 0;
end;
$function$;
CREATE OR REPLACE FUNCTION public.get_event_interest_count(event_id bigint, user_id uuid DEFAULT NULL::uuid)
 RETURNS TABLE(count bigint, has_interest boolean)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
select count(*) as interest_count,
	case
		when exists (
			select 1
			from public.events_interested
			where user_id = user_id
				and event_id = event_id
		) then true
		else false
	end as has_interest
from public.events_interested
where event_id = event_id;
$function$;
CREATE OR REPLACE FUNCTION public.get_guide_useful_count(guide_id bigint, user_id uuid DEFAULT NULL::uuid)
 RETURNS TABLE(count bigint, has_useful boolean)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
select count(*) as count,
	case
		when exists (
			select 1
			from public.guides_useful
			where user_id = user_id
				and guide_id = guide_id
		) then true
		else false
	end as has_useful
from public.guides_useful
where guide_id = guide_id;
$function$;
CREATE OR REPLACE FUNCTION public.handle_event_moderation_updates()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$ begin
insert into public.events_moderation (event_id, user_id, status, comment)
values (
		new.id,
		new.user_id,
		'pending'::moderation_status,
		'Pending moderation'
	);
return new;
end;
$function$;
CREATE OR REPLACE FUNCTION public.handle_events_moderation_notification()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare notification_type notification_type;
begin if new.status = 'pending' then notification_type := 'event_pending';
elsif new.status = 'changes_requested' then notification_type := 'event_changes_requested';
elsif new.status = 'approved' then notification_type := 'event_approved';
elsif new.status = 'rejected' then notification_type := 'event_rejected';
end if;
insert into public.notifications (user_id, type, data)
values (
		new.user_id,
		notification_type,
		jsonb_build_object('event_id', new.event_id)
	);
return new;
end;
$function$;
CREATE OR REPLACE FUNCTION public.handle_guide_moderation_updates()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$ begin
insert into public.guides_moderation (guide_id, user_id, status, comment)
values (
		new.id,
		new.user_id,
		'pending'::moderation_status,
		'Pending moderation'
	);
return new;
end;
$function$;
CREATE OR REPLACE FUNCTION public.handle_guides_moderation_notification()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare notification_type notification_type;
begin if new.status = 'pending' then notification_type := 'guide_pending';
elsif new.status = 'changes_requested' then notification_type := 'guide_changes_requested';
elsif new.status = 'approved' then notification_type := 'guide_approved';
elsif new.status = 'rejected' then notification_type := 'guide_rejected';
end if;
insert into public.notifications (user_id, type, data)
values (
		new.user_id,
		notification_type,
		jsonb_build_object('guide_id', new.guide_id)
	);
return new;
end;
$function$;
CREATE OR REPLACE FUNCTION public.handle_map_pin_moderation_updates()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$ begin
insert into public.map_pins_moderation (map_pin_id, user_id, status, comment)
values (
		new.id,
		new.user_id,
		'pending'::moderation_status,
		'Pending moderation'
	);
return new;
end;
$function$;
CREATE OR REPLACE FUNCTION public.handle_map_pins_moderation_notification()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare notification_type notification_type;
begin if new.status = 'pending' then notification_type := 'map_pin_pending';
elsif new.status = 'changes_requested' then notification_type := 'map_pin_changes_requested';
elsif new.status = 'approved' then notification_type := 'map_pin_approved';
elsif new.status = 'rejected' then notification_type := 'map_pin_rejected';
end if;
insert into public.notifications (user_id, type, data)
values (
		new.user_id,
		notification_type,
		jsonb_build_object('map_pin_id', new.map_pin_id)
	);
return new;
end;
$function$;
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$ begin
insert into public.user_roles (id, role)
values (new.id, 'user');
insert into public.profiles (id, email, type, display_name)
values (
		new.id,
		new.email,
		(
			select slug
			from public.user_types
			where is_default = true
		),
		new.raw_user_meta_data->>'display_name'
	);
return new;
end;
$function$;
create or replace view "public"."profiles_view" as  SELECT p.id,
    p.inserted_at,
    p.updated_at,
    p.email,
    p.type,
    p.display_name,
    p.description,
    p.avatar,
    p.age,
    p.profession,
    p.language,
    p.gender,
    p.cnum,
    p.sign_name,
    COALESCE(roles.role, 'user'::user_role) AS role
   FROM (profiles p
     LEFT JOIN user_roles roles ON ((p.id = roles.id)));
CREATE OR REPLACE FUNCTION public.update_user_types(types user_type[])
 RETURNS void
 LANGUAGE plpgsql
AS $function$
declare type user_type;
begin
delete from public.user_types
where true;
foreach type in array types loop
insert into public.user_types (slug, label, is_default)
values (type.slug, type.label, type.is_default);
end loop;
end;
$function$;
CREATE OR REPLACE FUNCTION public.verify_user_password(password text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$ begin return exists (
		select id
		from auth.users
		where id = auth.uid()
			and encrypted_password = crypt(password::text, auth.users.encrypted_password)
	);
end;
$function$;
create policy "Enable insert for users based on user_id"
on "public"."crowdsource_comments"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = user_id));
create policy "Enable read access for all users"
on "public"."crowdsource_comments"
as permissive
for select
to public
using (true);
create policy "Allow users to insert their own contributor record"
on "public"."islr_contributors"
as permissive
for insert
to public
with check ((auth.uid() = id));
create policy "Allow users to read their own contributor record"
on "public"."islr_contributors"
as permissive
for select
to public
using ((auth.uid() = id));
create policy "Allow all users to read all submission votes"
on "public"."islr_submission_votes"
as permissive
for select
to public
using (true);
create policy "Allow reviewers to vote on submissions that are not their own"
on "public"."islr_submission_votes"
as permissive
for insert
to public
with check (((auth.uid() = reviewer_id) AND (NOT (EXISTS ( SELECT 1
   FROM islr_submissions s
  WHERE ((s.id = islr_submission_votes.submission_id) AND (s.contributor_id = auth.uid())))))));
create policy "Allow all users to read all islr submissions"
on "public"."islr_submissions"
as permissive
for select
to public
using (true);
create policy "Allow contributors to insert their own submissions"
on "public"."islr_submissions"
as permissive
for insert
to public
with check ((auth.uid() = contributor_id));
create policy "Enable read access for all users"
on "public"."parameters"
as permissive
for select
to public
using (true);
create policy "Allow moderators to delete all signs"
on "public"."signs"
as permissive
for delete
to public
using (( SELECT authorize('guides.moderate'::user_permission) AS authorize));
create policy "Allow moderators to read all signs"
on "public"."signs"
as permissive
for select
to public
using (( SELECT authorize('signs.moderate'::user_permission) AS authorize));
create policy "Allow moderators to update all signs"
on "public"."signs"
as permissive
for update
to public
using (( SELECT authorize('guides.moderate'::user_permission) AS authorize));
create policy "Allow users to delete their own signs"
on "public"."signs"
as permissive
for delete
to public
using ((( SELECT authorize('signs.delete'::user_permission) AS authorize) AND (auth.uid() = created_by_user_id)));
create policy "Allow users to insert into table"
on "public"."signs"
as permissive
for insert
to public
with check ((( SELECT authorize('signs.create'::user_permission) AS authorize) AND (auth.uid() = created_by_user_id)));
create policy "Allow users to update their signs"
on "public"."signs"
as permissive
for update
to public
using ((( SELECT authorize('signs.update'::user_permission) AS authorize) AND (auth.uid() = created_by_user_id)))
with check ((auth.uid() = created_by_user_id));
create policy "Enable read access for all users"
on "public"."signs"
as permissive
for select
to public
using (true);
create policy "Allow users to delete their own favorited signs"
on "public"."signs_favorite"
as permissive
for delete
to public
using ((( SELECT authorize('signs.delete'::user_permission) AS authorize) AND (auth.uid() = user_id)));
create policy "Allow users to favorite their signs"
on "public"."signs_favorite"
as permissive
for insert
to public
with check ((( SELECT authorize('signs.create'::user_permission) AS authorize) AND (auth.uid() = user_id)));
create policy "Enable read access for all users"
on "public"."signs_favorite"
as permissive
for select
to public
using ((auth.uid() = user_id));
create policy "Allow moderators to insert signs moderation"
on "public"."signs_moderation"
as permissive
for insert
to public
with check (( SELECT authorize('signs.moderate'::user_permission) AS authorize));
create policy "Allow moderators to read all signs moderation"
on "public"."signs_moderation"
as permissive
for select
to public
using (( SELECT authorize('signs.moderate'::user_permission) AS authorize));
create policy "Allow users to read approved signs moderation"
on "public"."signs_moderation"
as permissive
for select
to public
using ((status = 'approved'::moderation_status));
create policy "Allow users to read their own signs moderation"
on "public"."signs_moderation"
as permissive
for select
to public
using ((auth.uid() = created_by_user_id));
create policy "Enable read access for all users"
on "public"."signs_moderation"
as permissive
for select
to public
using (true);
create policy "Allow users to rate signs"
on "public"."signs_rating"
as permissive
for insert
to public
with check ((( SELECT authorize('signs.create'::user_permission) AS authorize) AND (auth.uid() = user_id)));
create policy "Allow users to remove their sign rating"
on "public"."signs_rating"
as permissive
for delete
to public
using ((( SELECT authorize('signs.delete'::user_permission) AS authorize) AND (auth.uid() = user_id)));
create policy "Allow users to update their sign ratings"
on "public"."signs_rating"
as permissive
for update
to public
using ((( SELECT authorize('signs.create'::user_permission) AS authorize) AND (auth.uid() = user_id)));
create policy "Allow users to view their sign rating"
on "public"."signs_rating"
as permissive
for select
to public
using (true);
CREATE TRIGGER islr_submission_vote_limit_trigger BEFORE INSERT ON public.islr_submission_votes FOR EACH ROW EXECUTE FUNCTION check_islr_submission_vote_limit();
CREATE TRIGGER islr_submission_vote_trigger AFTER INSERT ON public.islr_submission_votes FOR EACH ROW EXECUTE FUNCTION handle_islr_submission_vote();
CREATE TRIGGER on_signs_insert AFTER INSERT ON public.signs FOR EACH ROW EXECUTE FUNCTION handle_sign_moderation_updates();
CREATE TRIGGER on_signs_update AFTER UPDATE ON public.signs FOR EACH ROW EXECUTE FUNCTION handle_sign_moderation_updates();
CREATE TRIGGER trigger_set_unaccented_name BEFORE INSERT OR UPDATE OF name ON public.signs FOR EACH ROW EXECUTE FUNCTION set_unaccented_name();
CREATE TRIGGER sign_notification_trigger AFTER INSERT ON public.signs_moderation FOR EACH ROW EXECUTE FUNCTION handle_signs_moderation_notification();
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.branding FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.events FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.guides FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.map_pins FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');
create policy "Enable insert for users "
  on "storage"."buckets"
  as permissive
  for insert
  to public
with check (true);
create policy "Allow users to upload their avatars 1ufimg_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'users'::text));
create policy "Allow users to upload videos 16id1q4_0"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'description'::text));
create policy "Allows game to list all videos 1zgtk0_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'lgp4fun'::text));
create policy "Allows users to upload converted .ogv videos 1zgtk0_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'lgp4fun'::text));
create policy "Allows users to upload images for lgp4fun 1ffg0oo_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'images'::text));

-- Grants
grant usage on schema public
to anon, authenticated, service_role;

grant select, insert, update, delete
on all tables in schema public
to anon, authenticated, service_role;

grant usage, select
on all sequences in schema public
to anon, authenticated, service_role;

grant execute
on all functions in schema public
to anon, authenticated, service_role;

-- Ensure tables created by future migrations receive the same permissions.
alter default privileges for role postgres in schema public
grant select, insert, update, delete on tables
to anon, authenticated, service_role;

alter default privileges for role postgres in schema public
grant usage, select on sequences
to anon, authenticated, service_role;

alter default privileges for role postgres in schema public
grant execute on functions
to anon, authenticated, service_role;