create table "public"."themes" (
    "id" bigint generated by default as identity primary key,
    "dictionary" character varying not null,
    "name" text,
    "is_parent" boolean,
    "children" character varying[],
    "parent" character varying
);

alter table "public"."themes" enable row level security;

create policy "Enable read access for all users"
on "public"."themes"
as permissive
for select
to public
using (true);

create policy "Authenticated users can create themes"
on "public"."themes"
as permissive
for insert
to authenticated
with check (true);

-- Seed
INSERT INTO "public"."themes" ("dictionary", "name", "is_parent", "children", "parent") VALUES
    -- Geral
    ('Geral', 'ALIMENTAÇÃO', true, ARRAY['CARNES', 'FRUTAS', 'PEIXES', 'VEGETAIS', 'PRATOS E BEBIDAS'], NULL),
    ('Geral', 'CARNES', false, NULL, 'ALIMENTAÇÃO'),
    ('Geral', 'FRUTAS', false, NULL, 'ALIMENTAÇÃO'),
    ('Geral', 'PEIXES', false, NULL, 'ALIMENTAÇÃO'),
    ('Geral', 'VEGETAIS', false, NULL, 'ALIMENTAÇÃO'),
    ('Geral', 'PRATOS E BEBIDAS', false, NULL, 'ALIMENTAÇÃO'),

    ('Geral', 'ANIMAIS', true, '{}', NULL),

    ('Geral', 'ARTES', true, ARRAY['MÚSICA', 'TEATRO'], NULL),
    ('Geral', 'MÚSICA', false, NULL, 'ARTES'),
    ('Geral', 'TEATRO', false, NULL, 'ARTES'),

    ('Geral', 'COMUNICAÇÃO', true, ARRAY['CUMPRIMENTOS', 'EMOÇÕES', 'EXPRESSÕES', 'INTRODUÇÃO PESSOAL', 'SAUDAÇÕES'], NULL),
    ('Geral', 'CUMPRIMENTOS', false, NULL, 'COMUNICAÇÃO'),
    ('Geral', 'EMOÇÕES', false, NULL, 'COMUNICAÇÃO'),
    ('Geral', 'EXPRESSÕES', false, NULL, 'COMUNICAÇÃO'),
    ('Geral', 'INTRODUÇÃO PESSOAL', false, NULL, 'COMUNICAÇÃO'),
    ('Geral', 'SAUDAÇÕES', false, NULL, 'COMUNICAÇÃO'),    

    ('Geral', 'CORES', true, '{}', NULL),

    ('Geral', 'CORPO HUMANO', true, '{}', NULL),
    
    ('Geral', 'CLUBES DE FUTEBOL', true, '{}', NULL),

    ('Geral', 'CLUBES E MARCAS', true, '{}', NULL),

    ('Geral', 'DESPORTO', true, '{}', NULL),

    ('Geral', 'EDIFÍCIOS E SERVIÇOS', true, ARRAY['ESCOLA'], NULL),
    ('Geral', 'ESCOLA', false, NULL, 'EDIFÍCIOS E SERVIÇOS'),

    ('Geral', 'EDUCAÇÃO', true, ARRAY['DISCIPLINAS'], NULL),
    ('Geral', 'DISCIPLINAS', false, NULL, 'EDUCAÇÃO'),

    ('Geral', 'EDUCAÇÃO PARA SURDOS', true, '{}', NULL),
    
    ('Geral', 'GEOGRAFIA E TERRITÓRIO', true, ARRAY['CONTINENTES', 'GEOGRAFIA LOCAL E GLOBAL', 'LISBOA E VALE DO TEJO', 
        'LOCALIDADES DA CIDADE DE LISBOA', 'LOCALIDADES DA MADEIRA', 'PAÍSES', 'REGIÕES AUTÓNOMAS DE PORTUGAL', 'REGIÕES E CIDADES DA MADEIRA',
        'ILHAS DOS AÇORES', 'LOCALIDADES DOS AÇORES', 'CIDADE DO PORTO', 'DISTRITO DO PORTO', 'LOCALIDADES DA CIDADE DO PORTO', 'CAPITAIS DE PAÍSES',
        'CIDADES DO MUNDO'], NULL),
    ('Geral', 'CONTINENTES', false, NULL, 'GEOGRAFIA E TERRITÓRIO'),
    ('Geral', 'GEOGRAFIA LOCAL E GLOBAL', false, NULL, 'GEOGRAFIA E TERRITÓRIO'),
    ('Geral', 'LISBOA E VALE DO TEJO', false, NULL, 'GEOGRAFIA E TERRITÓRIO'),
    ('Geral', 'LOCALIDADES DA CIDADE DE LISBOA', false, NULL, 'GEOGRAFIA E TERRITÓRIO'),
    ('Geral', 'LOCALIDADES DA MADEIRA', false, NULL, 'GEOGRAFIA E TERRITÓRIO'),
    ('Geral', 'PAÍSES', false, NULL, 'GEOGRAFIA E TERRITÓRIO'),
    ('Geral', 'REGIÕES AUTÓNOMAS DE PORTUGAL', false, NULL, 'GEOGRAFIA E TERRITÓRIO'),
    ('Geral', 'REGIÕES E CIDADES DA MADEIRA', false, NULL, 'GEOGRAFIA E TERRITÓRIO'),
    ('Geral', 'ILHAS DOS AÇORES', false, NULL, 'GEOGRAFIA E TERRITÓRIO'),
    ('Geral', 'LOCALIDADES DOS AÇORES', false, NULL, 'GEOGRAFIA E TERRITÓRIO'),
    ('Geral', 'CIDADE DO PORTO', false, NULL, 'GEOGRAFIA E TERRITÓRIO'),
    ('Geral', 'DISTRITO DO PORTO', false, NULL, 'GEOGRAFIA E TERRITÓRIO'),
    ('Geral', 'LOCALIDADES DA CIDADE DO PORTO', false, NULL, 'GEOGRAFIA E TERRITÓRIO'),   
    ('Geral', 'CAPITAIS DE PAÍSES', false, NULL, 'GEOGRAFIA E TERRITÓRIO'),
    ('Geral', 'CIDADES DO MUNDO', false, NULL, 'GEOGRAFIA E TERRITÓRIO'),

    ('Geral', 'LÍNGUA', true, ARRAY['ADJETIVOS', 'DACTILOLOGIA', 'NÚMERO CARDINAL', 'VERBOS', 'ADVÉRBIOS', 'NOMES E SUBSTANTIVOS',
    'NUMERAÇÃO', 'PRONOMES', 'NÚMEROS ARCAÍSMO', 'SENTIMENTOS E EMOÇÕES'], NULL),
    ('Geral', 'ADJETIVOS', false, NULL, 'LÍNGUA'),
    ('Geral', 'DACTILOLOGIA', false, NULL, 'LÍNGUA'),
    ('Geral', 'NÚMERO CARDINAL', false, NULL, 'LÍNGUA'),
    ('Geral', 'VERBOS', false, NULL, 'LÍNGUA'),
    ('Geral', 'ADVÉRBIOS', false, NULL, 'LÍNGUA'),
    ('Geral', 'NOMES E SUBSTANTIVOS', false, NULL, 'LÍNGUA'),
    ('Geral', 'NUMERAÇÃO', false, NULL, 'LÍNGUA'),
    ('Geral', 'PRONOMES', false, NULL, 'LÍNGUA'),
    ('Geral', 'NÚMEROS ARCAÍSMO', false, NULL, 'LÍNGUA'),
    ('Geral', 'SENTIMENTOS E EMOÇÕES', false, NULL, 'LÍNGUA'),

    ('Geral', 'MARCAS', true, '{}', NULL),

    ('Geral', 'MATEMÁTICA', true, '{}', NULL),
    
    ('Geral', 'NATUREZA', true, '{}', NULL),

    ('Geral', 'NOMES GESTUAIS', true, ARRAY['COMUNIDADE SURDA', 'PERSONALIDADES'], NULL),
    ('Geral', 'COMUNIDADE SURDA', false, NULL, 'NOMES GESTUAIS'),
    ('Geral', 'PERSONALIDADES', false, NULL, 'NOMES GESTUAIS'),
    
    ('Geral', 'NOTÁRIO', true, '{}', NULL),
    
    ('Geral', 'OBJETOS', true, ARRAY['MATERIAL DE ESCRITÓRIO', 'OBJETOS DA ESCOLA'], NULL),
    ('Geral', 'MATERIAL DE ESCRITÓRIO', false, NULL, 'OBJETOS'),
    ('Geral', 'OBJETOS DA ESCOLA', false, NULL, 'OBJETOS'),
    
    ('Geral', 'PARTES DA CASA', true, ARRAY['CASA E DIVISÕES', 'CASA DE BANHO', 'COZINHA', 'DESPENSA', 'QUARTO', 'SALA DE ESTAR'], NULL),
    ('Geral', 'CASA E DIVISÕES', false, NULL, 'PARTES DA CASA'),
    ('Geral', 'CASA DE BANHO', false, NULL, 'PARTES DA CASA'),
    ('Geral', 'COZINHA', false, NULL, 'PARTES DA CASA'),
    ('Geral', 'DESPENSA', false, NULL, 'PARTES DA CASA'),
    ('Geral', 'QUARTO', false, NULL, 'PARTES DA CASA'),
    ('Geral', 'SALA DE ESTAR', false, NULL, 'PARTES DA CASA'),    

    ('Geral', 'REDES SOCIAIS', true, '{}', NULL),

    ('Geral', 'SAÚDE', true, '{}', NULL),
    
    ('Geral', 'SOCIEDADE', true, ARRAY['CIDADANIA E RESPONSABILIDADE', 'FAMÍLIA', 'PROFISSÕES', 'CELEBRAÇÕES E RELIGIÃO', 'GÉNERO', 'RELIGIÃO E TRADIÇÕES AÇOREANAS', 'VALORES ÉTICOS', 'FESTIVIDADES', 'ORIENTAÇÃO SEXUAL', 'TRABALHO'], NULL),
    ('Geral', 'CIDADANIA E RESPONSABILIDADE', false, NULL, 'SOCIEDADE'),
    ('Geral', 'FAMÍLIA', false, NULL, 'SOCIEDADE'),
    ('Geral', 'PROFISSÕES', false, NULL, 'SOCIEDADE'),
    ('Geral', 'CELEBRAÇÕES E RELIGIÃO', false, NULL, 'SOCIEDADE'),
    ('Geral', 'GÉNERO', false, NULL, 'SOCIEDADE'),
    ('Geral', 'RELIGIÃO E TRADIÇÕES AÇOREANAS', false, NULL, 'SOCIEDADE'),
    ('Geral', 'VALORES ÉTICOS', false, NULL, 'SOCIEDADE'),
    ('Geral', 'FESTIVIDADES', false, NULL, 'SOCIEDADE'),
    ('Geral', 'ORIENTAÇÃO SEXUAL', false, NULL, 'SOCIEDADE'),
    ('Geral', 'TRABALHO', false, NULL, 'SOCIEDADE'),

    ('Geral', 'TEMPO E CALENDÁRIO', true, ARRAY['DIAS DA SEMANA', 'ESTAÇÕES DO ANO', 'MESES DO ANO', 'PARTES DO DIA', 'TEMPO'], NULL),
    ('Geral', 'DIAS DA SEMANA', false, NULL, 'TEMPO E CALENDÁRIO'),
    ('Geral', 'ESTAÇÕES DO ANO', false, NULL, 'TEMPO E CALENDÁRIO'),
    ('Geral', 'MESES DO ANO', false, NULL, 'TEMPO E CALENDÁRIO'),
    ('Geral', 'PARTES DO DIA', false, NULL, 'TEMPO E CALENDÁRIO'),
    ('Geral', 'TEMPO', false, NULL, 'TEMPO E CALENDÁRIO'),

    ('Geral', 'TRANSPORTES E COMUNICAÇÕES', true, '{}', NULL),
    
    ('Geral', 'VESTUÁRIO', true, '{}', NULL),

    
    -- 1º CEB
    ('1º CEB', 'MATEMÁTICA', true, ARRAY['ESTASTÍSTICAS E PROBABILIDADES', 'FRAÇÕES E DÉCIMAS', 'GEOMETRIA', 'MEDIDAS', 'NÚMEROS', 'OPERAÇÕES MATEMÁTICAS', 'RELAÇÕES E COMPARAÇÕES', 'SIMETRIA E PADRÕES'], NULL),
    ('1º CEB', 'ESTASTÍSTICAS E PROBABILIDADES', false, NULL, 'MATEMÁTICA'),
    ('1º CEB', 'FRAÇÕES E DÉCIMAS', false, NULL, 'MATEMÁTICA'),
    ('1º CEB', 'GEOMETRIA', false, NULL, 'MATEMÁTICA'),
    ('1º CEB', 'MEDIDAS', false, NULL, 'MATEMÁTICA'),
    ('1º CEB', 'NÚMEROS', false, NULL, 'MATEMÁTICA'),
    ('1º CEB', 'OPERAÇÕES MATEMÁTICAS', false, NULL, 'MATEMÁTICA'),
    ('1º CEB', 'RELAÇÕES E COMPARAÇÕES',  false, NULL, 'MATEMÁTICA'),
    ('1º CEB', 'SIMETRIA E PADRÕES', false, NULL, 'MATEMÁTICA'),

    ('1º CEB', 'PORTUGUÊS', true, ARRAY['ADJETIVOS', 'DACTILOLOGIA', 'SAUDAÇÕES', 'VERBOS'], NULL),
    ('1º CEB', 'ADJETIVOS', false, NULL, 'PORTUGUÊS'),
    ('1º CEB', 'DACTILOLOGIA', false, NULL, 'PORTUGUÊS'),
    ('1º CEB', 'SAUDAÇÕES', false, NULL, 'PORTUGUÊS'),
    ('1º CEB', 'VERBOS', false, NULL, 'PORTUGUÊS'),

    ('1º CEB', 'ESTUDO DO MEIO', true, ARRAY['ALIMENTOS E NUTRIÇÃO', 'AMBIENTE NATURAL', 'ANIMAIS', 'CIDADANIA E RESPONSABILIDADE',
        'CORES', 'CORPO HUMANO E SAÚDE', 'DIAS DA SEMANA', 'EMOÇÕES', 'ESTAÇÕES DO ANO', 'FAMÍLIA E SOCIEDADE', 'GEOGRAFIA LOCAL E GLOBAL', 'MATÉRIA E ENERGIA',
        'MEIOS DE TRANSPORTE E COMUNICAÇÕES', 'MESES DO ANO', 'OBJETOS DA ESCOLA', 'PARTES DA CASA', 'CASA E DIVISÕES', 'PROFISSÕES', 'VESTUÁRIO',
        'INSTRUMENTOS DE MEDIÇÃO'], NULL),
    ('1º CEB', 'ALIMENTOS E NUTRIÇÃO', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'AMBIENTE NATURAL', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'ANIMAIS', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'CIDADANIA E RESPONSABILIDADE', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'CORES', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'CORPO HUMANO E SAÚDE', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'DIAS DA SEMANA', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'EMOÇÕES', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'ESTAÇÕES DO ANO', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'FAMÍLIA E SOCIEDADE', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'GEOGRAFIA LOCAL E GLOBAL', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'MATÉRIA E ENERGIA', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'MEIOS DE TRANSPORTE E COMUNICAÇÕES', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'MESES DO ANO', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'OBJETOS DA ESCOLA', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'PARTES DA CASA', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'CASA E DIVISÕES', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'PROFISSÕES', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'VESTUÁRIO', false, NULL, 'ESTUDO DO MEIO'),
    ('1º CEB', 'INSTRUMENTOS DE MEDIÇÃO', false, NULL, 'ESTUDO DO MEIO'),

    ('1º CEB', 'EDUCAÇÃO ARTÍSTICA', true, ARRAY['ARTES VISUAIS', 'MÚSICA', 'TEATRO', 'ELEMENTOS BÁSICOS DA ARTE'], NULL),
    ('1º CEB', 'ARTES VISUAIS', false, NULL, 'EDUCAÇÃO ARTÍSTICA'),
    ('1º CEB', 'MÚSICA', false, NULL, 'EDUCAÇÃO ARTÍSTICA'),
    ('1º CEB', 'TEATRO', false, NULL, 'EDUCAÇÃO ARTÍSTICA'),
    ('1º CEB', 'ELEMENTOS BÁSICOS DA ARTE', false, NULL, 'EDUCAÇÃO ARTÍSTICA'),

    -- Terminologia
    ('Terminologia', 'CIÊNCIAS DA LINGUAGEM', true, '{}', NULL),

    ('Terminologia', 'MEDICINA', true, '{}', NULL),

    -- Crowdsource
    ('Crowdsource', 'Proposta - Em Discussão', true, '{}', NULL),

    ('Crowdsource', 'Proposta - Aceite', true, '{}', NULL),

    ('Crowdsource', 'Proposta - Adicionada', true, '{}', NULL),

    -- Outros
    ('Outros', 'ação', true, '{}', NULL),

    ('Outros', 'tema por definir', true, '{}', NULL);